" Vim color file - Gene
" Generated by http://atsushimori.com

set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = "Gene"

" Base
hi Visual guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE ctermfg=0 ctermbg=15 cterm=none
hi NonText guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none


" Base
hi MoreMsg guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Question guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Normal guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Special guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi StatusLineNC ctermfg=232 ctermbg=0 cterm=none
hi StatusLine   ctermfg=232 ctermbg=0 cterm=none
hi EndOfBuffer guifg=#000 guibg=#000 guisp=NONE gui=NONE ctermfg=0 ctermbg=0 cterm=NONE
hi Constant guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi PreProc guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Type guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Function guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Statement guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Directory guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi Character guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=none
hi String guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=underline

" Dark
hi LineNr guifg=#184563 guibg=NONE guisp=NONE gui=NONE ctermfg=0 ctermbg=0 cterm=NONE
hi VertSplit guifg=#184563 guibg=NONE guisp=NONE gui=NONE ctermfg=233 ctermbg=0 cterm=NONE
hi StatusLine guifg=#184563 guibg=NONE guisp=NONE gui=NONE ctermfg=233 ctermbg=0 cterm=NONE

" Light gray
hi Conditional guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=245 ctermbg=0 cterm=NONE
hi SpecialKey guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=0 cterm=NONE

" Gray
hi Comment guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=240 ctermbg=0 cterm=NONE
hi Boolean guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=240 ctermbg=0 cterm=none

" Key - Font
hi Underlined guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=none
hi Search guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi IncSearch guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi LightlineLeft_normal_0 guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi LightlineLeft_normal_tabsel_0 guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi LightlineLeft_active_tabsel_0 guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi LightlineLeft_normal_tabsel_0 guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi LightlineLeft_normal_0 guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE
hi LightlineLeft_active_0 guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=0 cterm=NONE

" Key - Background
hi Todo guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=0 ctermbg=220 cterm=none
hi Pmenu guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=0 ctermbg=220 cterm=none

" Key - Background - Error
hi Ignore guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=197 ctermbg=233 cterm=NONE
hi ErrorMsg guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=197 ctermbg=0 cterm=NONE
hi Error guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=197 ctermbg=0 cterm=NONE
