" Vim color file - Gene
" Generated by http://atsushimori.com
set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = "Gene"

" Base
hi Normal guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=233 cterm=none
hi Special guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=233 cterm=none
hi StatusLineNC ctermfg=232 ctermbg=0 cterm=bold
hi StatusLine   ctermfg=232 ctermbg=0 cterm=bold
hi EndOfBuffer guifg=#000 guibg=#000 guisp=NONE gui=NONE ctermfg=0 ctermbg=0 cterm=NONE
hi Constant guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=233 cterm=none
hi PreProc guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=233 cterm=none
hi Type guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=233 cterm=none
hi Function guifg=#ffffff guibg=#121212 guisp=NONE gui=NONE ctermfg=15 ctermbg=233 cterm=none


" Dark
hi LineNr guifg=#184563 guibg=NONE guisp=NONE gui=NONE ctermfg=233 ctermbg=0 cterm=NONE
hi VertSplit guifg=#184563 guibg=NONE guisp=NONE gui=NONE ctermfg=233 ctermbg=0 cterm=NONE
hi StatusLine guifg=#184563 guibg=NONE guisp=NONE gui=NONE ctermfg=233 ctermbg=0 cterm=NONE

" Light gray
hi Conditional guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=245 ctermbg=233 cterm=NONE
hi Statement guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=245 ctermbg=233 cterm=NONE
hi SpecialKey guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=245 ctermbg=233 cterm=NONE

" Gray
hi Comment guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=237 ctermbg=233 cterm=NONE
hi Directory guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=237 ctermbg=233 cterm=NONE
hi String guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=238 ctermbg=233 cterm=NONE
hi Character guifg=#184563 guibg=#121212 guisp=NONE gui=NONE ctermfg=238 ctermbg=233 cterm=NONE

" Key - Font
hi Boolean      guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=233 cterm=none
hi Underlined      guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=233 cterm=none
hi Search guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=233 cterm=NONE
hi IncSearch guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=220 ctermbg=233 cterm=NONE

" Key - Background
hi Todo      guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=0 ctermbg=220 cterm=none
hi Pmenu      guifg=#005fd7 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=0 ctermbg=220 cterm=none

" Key - Background - Error
hi Ignore guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=197 ctermbg=233 cterm=NONE
hi ErrorMsg guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=197 ctermbg=233 cterm=NONE
hi Error guifg=#184563 guibg=#ffd700 guisp=NONE gui=NONE ctermfg=197 ctermbg=233 cterm=NONE
